paragraphs = [
    "Global warming is one of the most pressing environmental issues facing our planet today",
    "Reducing carbon emissions is essential to slowing global warming.",
    "Renewable energy sources like solar and wind power are key to sustainability.",
    "Recycling and reusing materials can significantly reduce environmental waste.",
    "Planting trees helps absorb carbon dioxide from the atmosphere.",
    "Melting glaciers are a visible sign of rising global temperatures.",
    "The ocean absorbs most of the heat caused by greenhouse gas emissions.",
    "Electric vehicles produce fewer emissions than gasoline-powered cars.",
    "Single-use plastics contribute to pollution in oceans and landfills.",
    "Switching to energy-efficient appliances helps reduce electricity consumption.",
    "Public transportation reduces the number of cars on the road and cuts emissions.",
    "Biodiversity is threatened by habitat loss and climate change.",
    "Sustainable agriculture supports food production while protecting the planet.",
    "Water conservation is vital in regions affected by drought and heatwaves.",
    "Deforestation increases the amount of carbon dioxide in the atmosphere.",
    "Rising sea levels threaten coastal communities around the world.",
    "Composting organic waste reduces methane emissions from landfills.",
    "Educating others about climate change promotes environmental action.",
    "Global cooperation is necessary to combat the effects of climate change.",
    "Buying local and seasonal food reduces the carbon footprint of transportation.",
    "Green buildings are designed to minimize energy and water use.",
    "Extreme weather events are becoming more frequent due to climate change.",
    "Overfishing and ocean acidification threaten marine ecosystems.",
    "Advocating for policy changes is an important part of climate activism.",
    "Using a reusable water bottle helps cut down on plastic waste.",
    "Switching to LED bulbs can lower energy use and utility bills.",
    "Air pollution contributes to climate change and harms human health.",
    "Supporting companies with sustainable practices encourages green innovation.",
    "Climate justice ensures vulnerable communities are not left behind.",
    "Every small action counts in the fight against climate change."
]
